import pandas as pd
import torch
from datasets import load_dataset, Dataset, concatenate_datasets
from transformers import AutoModelForSequenceClassification, AutoTokenizer, Trainer, TrainingArguments

def main():
    print("--- Initializing Adversarial Training Pipeline ---")
    
    # 1. Load the pre-trained model and tokenizer
    # We load the exact same model TextFooler just attacked
    model_name = "textattack/bert-base-uncased-imdb"
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSequenceClassification.from_pretrained(model_name)

    # 2. Extract the Adversarial Data
    print("Extracting adversarial examples from CSV...")
    # Load the results generated by your 6-hour run
    # Adjust the filename if you named it differently
    df = pd.read_csv("attack_results_1000.csv")
    
    # We only want to train on the text that successfully broke the model
    successful_attacks = df[df['result_type'] == 'Successful']
    
    # Clean the text (TextAttack sometimes wraps flipped words in brackets like [[word]])
    adv_texts = successful_attacks['perturbed_text'].str.replace(r'\[\[|\]\]', '', regex=True).tolist()
    adv_labels = successful_attacks['ground_truth_output'].tolist()

    # Convert to Hugging Face Dataset format
    adv_dataset = Dataset.from_dict({"text": adv_texts, "label": adv_labels})

    # 3. Load a subset of the Original Clean Data
    # We mix the adversarial examples with clean examples so the model doesn't 
    # "forget" how to read normal English (Catastrophic Forgetting).
    print("Fetching original IMDB training data...")
    clean_dataset = load_dataset("imdb", split="train[:2000]") # Taking 2000 clean samples

    # -> NEW LINE: Force the adversarial dataset to adopt the official ClassLabel schema
    adv_dataset = adv_dataset.cast(clean_dataset.features)
    
    # 4. Combine and Shuffle
    print("Fusing clean and adversarial datasets...")
    mixed_dataset = concatenate_datasets([clean_dataset, adv_dataset]).shuffle(seed=42)

    # 5. Tokenization Function
    def tokenize_data(examples):
        return tokenizer(examples["text"], padding="max_length", truncation=True, max_length=256)

    print("Tokenizing data...")
    tokenized_dataset = mixed_dataset.map(tokenize_data, batched=True)

    # 6. Configure the Training Loop
    # Training is mathematically heavier than inference. We set the batch size 
    # to fit comfortably within 16GB of VRAM.
    training_args = TrainingArguments(
        output_dir="./hardened_bert",
        num_train_epochs=3,              # 3 passes over the new mixed dataset
        per_device_train_batch_size=16,  # Optimized for 16GB VRAM
        logging_steps=50,
        save_strategy="epoch",
        learning_rate=2e-5,              # A small learning rate so we don't wreck the pre-trained weights
        weight_decay=0.01,
        report_to="none"                 # Disables external logging
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_dataset,
    )

    # 7. Execute Training
    print("Initiating VRAM allocation and training loop...")
    trainer.train()

    # 8. Save the Hardened Model
    print("Saving the hardened model to disk...")
    trainer.save_model("./hardened_bert_final")
    tokenizer.save_pretrained("./hardened_bert_final")
    print("--- Adversarial Retraining Complete ---")

if __name__ == "__main__":
    main()